package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "revio-metadata-to-samplename",
	Short: "Extracts sample names from PacBio Revio metadata XML files",
	Long: `A command-line tool for extracting sample names from PacBio Revio metadata XML files.
This tool parses the XML metadata files generated by PacBio Revio sequencing systems
and extracts the sample names, optionally including the results folder paths.`,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	// Add child commands here if needed
}
